apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: alfa
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZWU=          # ← подставьте ваши base64
  POSTGRES_PASSWORD: cG9zdGdyZWU=
  POSTGRES_DB: cG9zdGdyZWU=