apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: alfa
type: Opaque
stringData:
  # Замените значения на ваши реальные данные!
  ConnectionStrings__DefaultConnection: "Host=postgres-svc;Database=postgree;Username=postgree;Password=postgree"