apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: alfa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path    # ← встроен в k3s из коробки
  resources:
    requests:
      storage: 10Gi