server {
    listen 80;
    
    # Статика
    location / {
        proxy_pass http://react:3000;
    }
    
    # API прокси
    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}