apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: alfa
data:
  nginx.conf: |
    server {
      listen 88;
      server_name _;

      # Раздача статики React (SPA)
      location / {
          root /usr/share/nginx/html;
          index index.html;
          
          try_files $uri $uri/ /index.html;
          
          location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
              expires 1y;
              add_header Cache-Control "public, immutable";
              try_files $uri =404;
          }
      }
      
      # Проксирование на бэкенд
      location /api/ {
          # 1. Динамический резолвер DNS (обязательно для K8s)
          resolver kube-dns.kube-system.svc.cluster.local valid=10s;

          # 2. Объявляем переменную. Это заставляет Nginx обновлять IP при каждом запросе!
          set $backend_upstream http://backend-svc:8080;
          
          # 3. Используем переменную в proxy_pass (БЕЗ слэша на конце!)
          # Теперь /api/users уйдет на бэкенд как /api/users
          proxy_pass $backend_upstream;
          
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
      }
      
      # Запрет доступа к скрытым файлам
      location ~ /\. {
          deny all;
      }
    }

