apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: alfa
spec:
  type: NodePort           # ← Тип сервиса
  selector:
    app: frontend
  ports:
    - port: 88             # Порт внутри кластера
      targetPort: 88       # Порт внутри контейнера
      nodePort: 30088  